# Module 6 Exercises - Correlation and Models

### Exercise 1:

From the datasets folder, load the "tamiami.csv" file as a dataframe. Rename the columns (in order) to the following:

- location
- sales
- employees
- restaurants
- foodcarts
- price

Then do a correlation table on that dataframe. What features (columns) are correlated? What features aren't correlated?

In [1]:
import pandas as pd
import numpy as np

In [2]:
Location = "datasets/tamiami.csv"
df = pd.read_csv(Location)

df.head()

,Cart Location,Hot Dog Sales,Employees in Nearby Office Buildings,Num of Nearby Restaurants,Num of Other Food Carts Nearby,Price
0,1,100,1600,8,12,4.16
1,2,80,1200,6,13,4.63
2,3,450,2800,19,6,0.50
3,4,580,4300,19,2,0.47
4,5,100,1400,6,13,4.24

In [3]:
df.columns

Index(['Cart Location', 'Hot Dog Sales',
       'Employees in Nearby Office Buildings', 'Num of Nearby Restaurants',
       'Num of Other Food Carts Nearby', 'Price'],
      dtype='object')

In [9]:
df.rename(columns={'Cart Location' : 'location','Hot Dog Sales' : 'sales',
                           'Employees in Nearby Office Buildings':'employees', 
                           'Num of Nearby Restaurants':'restaurant',
                           'Num of Other Food Carts Nearby':'foodcarts','Price':'price' }, inplace=True)
df.head()

   location  sales  employees  restaurant  foodcarts  price
0         1    100       1600           8         12   4.16
1         2     80       1200           6         13   4.63
2         3    450       2800          19          6   0.50
3         4    580       4300          19          2   0.47
4         5    100       1400           6         13   4.24

In [6]:
df.corr()

            location     sales  employees  restaurant  foodcarts     price
location    1.000000  0.042705  -0.068923    0.049701   0.077219 -0.138444
sales       0.042705  1.000000   0.943238    0.913674  -0.919762 -0.966378
employees  -0.068923  0.943238   1.000000    0.856976  -0.874692 -0.881540
restaurant  0.049701  0.913674   0.856976    1.000000  -0.761793 -0.933951
foodcarts   0.077219 -0.919762  -0.874692   -0.761793   1.000000  0.860154
price      -0.138444 -0.966378  -0.881540   -0.933951   0.860154  1.000000

### Exercise 2:

Using the dataframe from the previous exercise, choose features (columns) to create a linear regression formula to predict sales. Try it with and without the y-intercept. How does it make a difference? Does adding or removing features in your model formula make a difference in the output?

In [11]:
import statsmodels.formula.api as smf

In [14]:
result = smf.ols('sales ~ employees + restaurant', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.931
Model:                            OLS   Adj. R-squared:                  0.926
Method:                 Least Squares   F-statistic:                     183.5
Date:                Wed, 21 Aug 2019   Prob (F-statistic):           1.92e-16
Time:                        11:05:46   Log-Likelihood:                -156.98
No. Observations:                  30   AIC:                             320.0
Df Residuals:                      27   BIC:                             324.2
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -147.8062     23.004     -6.425      0.000    -195.007    -100.605
employees      0.1226      0.020      6.172      0.000       0.082       0.163
restaurant    13.7409      3.386      4.058      0.000       6.792      20.689
==============================================================================
Omnibus:                        3.067   Durbin-Watson:                   1.698
Prob(Omnibus):                  0.216   Jarque-Bera (JB):                1.417
Skew:                           0.087   Prob(JB):                        0.492
Kurtosis:                       1.950   Cond. No.                     5.81e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.81e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [19]:
result = smf.ols('sales ~ employees', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.890
Model:                            OLS   Adj. R-squared:                  0.886
Method:                 Least Squares   F-statistic:                     225.8
Date:                Wed, 21 Aug 2019   Prob (F-statistic):           6.23e-15
Time:                        11:13:28   Log-Likelihood:                -164.12
No. Observations:                  30   AIC:                             332.2
Df Residuals:                      28   BIC:                             335.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -129.0763     28.078     -4.597      0.000    -186.592     -71.561
employees      0.1917      0.013     15.028      0.000       0.166       0.218
==============================================================================
Omnibus:                        3.436   Durbin-Watson:                   1.748
Prob(Omnibus):                  0.179   Jarque-Bera (JB):                1.545
Skew:                          -0.147   Prob(JB):                        0.462
Kurtosis:                       1.928   Cond. No.                     5.69e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.69e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [20]:
result = smf.ols('sales ~ employees + restaurant-1', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     249.0
Date:                Wed, 21 Aug 2019   Prob (F-statistic):           1.47e-18
Time:                        11:15:01   Log-Likelihood:                -170.90
No. Observations:                  30   AIC:                             345.8
Df Residuals:                      28   BIC:                             348.6
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
employees      0.0851      0.030      2.871      0.008       0.024       0.146
restaurant     9.3747      5.181      1.809      0.081      -1.238      19.987
==============================================================================
Omnibus:                        3.099   Durbin-Watson:                   1.242
Prob(Omnibus):                  0.212   Jarque-Bera (JB):                1.911
Skew:                           0.387   Prob(JB):                        0.385
Kurtosis:                       2.035   Cond. No.                         837.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""